In [1]:
import numpy as np

# arange()

In [2]:
a=np.arange(1,12,2)**2

In [3]:
list(a)

[1, 9, 25, 49, 81, 121]

In [4]:
lst=a.reshape(2,3)

In [5]:
lst

array([[  1,   9,  25],
       [ 49,  81, 121]])

In [8]:
lst1=np.array([[1,2,3],[4,5,6]])
lst1.shape

(2, 3)

In [9]:
lst1.ndim # returns number of dimensions

2

In [10]:
print(f"Type:{type(lst1)}")

Type:<class 'numpy.ndarray'>


In [12]:
b=np.arange(1,10,0.5,dtype='float')
b

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [13]:
c=np.arange(10,0,-0.5)
c

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5])

# linspace

In [15]:
x=np.linspace(0,10,11)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
y=np.linspace(50,0,11)
y

array([50., 45., 40., 35., 30., 25., 20., 15., 10.,  5.,  0.])

# zero's and zero's_like

In [ ]:
np.zeros((pass shape))

In [20]:
np.zeros((2,2,2),dtype=int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [21]:
np.zeros((2,2,2),dtype=int).ndim

3

In [32]:
a=np.array([1,2,3,4,5])
lst2=np.zeros_like(a)
lst2

array([0, 0, 0, 0, 0])

# One's, One's_like

In [34]:
a=np.ones((3,2,3),dtype=int)

In [35]:
print(a) # 3-->2D matrices, Each 2D matrix has 2 rows and 3 columns

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [36]:
z=np.ones_like(a)
z

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [39]:
cv=np.identity(4)

In [40]:
cv

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
d=np.arange(36).reshape(3,2,6)
d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])